### ISSUE TITLE
poppler version

### ISSUE THREAD

**Issue by nerijus** [clbr/flaxpdf#1]
Is it a reason it requires version >= 0.31? I changed in configure to require >=0.26 and it compiled and works on F21.

**Comment by clbr** [comment]
It has not been tested with earlier versions. Your distro will likely
update to latest poppler soon anyway.

**Comment by nerijus** [comment]
No, Fedora 21 will not update to a newer poppler version. F22 will. But if flaxpdf does not specifically require some poppler features, I'd suggest removing version check or at least lower it.

**Comment by clbr** [comment]
That would require testing all poppler versions until something breaks (and not just compile-time, there have been subtle threading bugs, etc.). Seems a lot of work for something that will solve itself in some months, no?

**Comment by nerijus** [comment]
According to http://koji.fedoraproject.org/koji/packageinfo?packageID=132 F22 will most likely have 0.30.0.

**Comment by clbr** [comment]
Quoting from the FLTK ml, where this also came up:

> While there is no hard dependency on that version (ie, wouldn't compile on an earlier one), it is a matter of both user experience and testing. FlaxPDF has only been tested with 0.31, and so can't be guaranteed to work with earlier versions.
> The other part is the user experience, every version of poppler contains important bugfixes, often crashers. If I allowed an earlier version with already known and fixed bugs, users would blame the application when a PDF crashes it, even though the bug is in poppler, and already fixed in a later version.
> 
> From a user's POV, they won't care which component is at fault when a program crashes, it reflects poorly on the program in their mind.

As 0.31 contains at least two such serious fixes, I won't allow 0.30 even if it is too late for Fedora 22.

**Comment by nerijus** [comment]
Serious fixes (especially crashes) are usually backported. Well, but it's up to you, I see you don't want to support earlier versions. I'll use configure patch for now.
