### ISSUE TITLE
Build fails with poppler-0.74.0

### ISSUE THREAD

**Issue by juanitotc** [clbr/flaxpdf#5]
error below fixed with:
sed -i 's/getCString/c_str/' src/view.cpp

g++ -flto -fuse-linker-plugin -mtune=generic -Os -pipe -fno-exceptions -fno-rtti -DHAVE_CONFIG_H -I.  -DDATADIR=\"/usr/local/share/flaxpdf\" -DLOCALEDIR=\"/usr/local/share/locale\"   -fopenmp -pthread -isystem /usr/local/include -fvisibility-inlines-hidden -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -isystem /usr/local/include/poppler -isystem /usr/local/include -Wall -Wextra -ffunction-sections -fdata-sections -MT view.o -MD -MP -MF .deps/view.Tpo -c -o view.o view.cpp
view.cpp: In member function 'virtual int pdfview::handle(int)':
view.cpp:397:36: error: 'class GooString' has no member named 'getCString'
  397 |     const char * const cstr = str->getCString();
      |                                    ^~~~~~~~~~
make[2]: *** [Makefile:437: view.o] Error 1
make[2]: Leaving directory '/usr/src/flaxpdf/src'

**Comment by clbr** [comment]
Should be fixed, please try.

**Comment by juanitotc** [comment]
Yep - that works
